#!/bin/sh

action="$1"

#systemctl stop atlas
#systemctl disable atlas
#systemctl stop var-atlasdata.mount
#systemctl disable var-atlasdata.mount

# init.d version
service_name="atlas"
update-rc.d $service_name remove

rmdir /var/atlasdata
rm -r /var/atlas-probe/.ssh
rm -r /var/atlas-probe/bin
rm -r /var/atlas-probe/crons
if [ X"$action" = Xupgrade ]
then
	: # Keep key material
else
	rm -r /var/atlas-probe/etc
fi
rm -r /var/atlas-probe/run
rm -r /var/atlas-probe/state
rm -r /var/atlas-probe/status

LOGDIR=/var/log/atlas
rm -rf $LOGDIR

rm /etc/sudoers.d/atlas # Remove sudo configuration
